v0.99c replaced which with hash

diff --git a/a7crypt b/a7crypt
--- a/a7crypt
+++ b/a7crypt
@@ -1,5 +1,5 @@
 #!/bin/bash
-# a7crypt v0.99b last mod 2011/11/28
+# a7crypt v0.99c last mod 2011/11/28
 # Latest version at <http://github.com/ryran/b19scripts>
 # Copyright 2011 Ryan Sawhill <ryan@b19.org>
 #
@@ -44,19 +44,19 @@ trap ">$A7/pass; rm $A7/msg* 2>/dev/null" EXIT
 
 ## Here we create our preset environments
 init_env_GPG2() {
-	MODE=GPG2; SWITCH_TO=OpenSSL
-	ENCRYPT="gpg2 --batch -ac --force-mdc --passphrase-file $A7/pass $A7/msg"
-	DECRYPT="gpg2 --batch -d --passphrase-file $A7/pass --output $A7/msg $A7/msg.asc"
+  mode=GPG2; switch_to=OpenSSL
+  encrypt="gpg2 --batch -ac --force-mdc --passphrase-file $A7/pass $A7/msg"
+  decrypt="gpg2 --batch -d --passphrase-file $A7/pass --output $A7/msg $A7/msg.asc"
 }
 init_env_GPG() {
-	MODE=GPG; SWITCH_TO=OpenSSL
-	ENCRYPT="gpg -ac --force-mdc --passphrase-file $A7/pass $A7/msg"
-	DECRYPT="gpg -d --passphrase-file $A7/pass --output $A7/msg $A7/msg.asc"
+  mode=GPG; switch_to=OpenSSL
+  encrypt="gpg -ac --force-mdc --passphrase-file $A7/pass $A7/msg"
+  decrypt="gpg -d --passphrase-file $A7/pass --output $A7/msg $A7/msg.asc"
 }
 init_env_OPENSSL() {
-	MODE=OpenSSL-AES; SWITCH_TO=GPG
-	ENCRYPT="openssl aes-256-cbc -a -salt -pass file:$A7/pass -in $A7/msg -out $A7/msg.asc"
-	DECRYPT="openssl aes-256-cbc -a -d -pass file:$A7/pass -in $A7/msg.asc -out $A7/msg"
+  mode=OpenSSL-AES; switch_to=GPG
+  encrypt="openssl aes-256-cbc -a -salt -pass file:$A7/pass -in $A7/msg -out $A7/msg.asc"
+  decrypt="openssl aes-256-cbc -a -d -pass file:$A7/pass -in $A7/msg.asc -out $A7/msg"
 }
 
 
@@ -66,52 +66,52 @@ init_env_OPENSSL() {
 MAIN() {                                                                    #---
 
 ## Here we warn the user about using OpenSSL, and give a chance to hide warnings
-if [[ $MODE = OpenSSL-AES && ! -f /tmp/$zero.nowarn.$UID ]]; then
-	echo -en "You're running $zero in OpenSSL mode--either by choice, or because we could not locate GPG/GPG2.\nThis mode uses the command 'openssl aes-256-cbc' to encrypt your text.\nThe corresponding command for decryption is 'openssl aes-256-cbc -a -d' <-- which might be useful to know if you were to lose this app, because OpenSSL doesn't add any pretty info to your encrypted message like GPG, nor is OpenSSL simple-minded enough to decrypt a block of text you pass to it without using the proper arguments." | zenity --text-info --title="$zero [$MODE]: Warning" --cancel-label="Understood, don't tell me for a while" --width=724 --height=210 || touch /tmp/$zero.nowarn.$UID
+if [[ $mode = OpenSSL-AES && ! -f /tmp/$zero.nowarn.$UID ]]; then
+  echo -en "You're running $zero in OpenSSL mode--either by choice, or because we could not locate GPG/GPG2.\nThis mode uses the command 'openssl aes-256-cbc' to encrypt your text.\nThe corresponding command for decryption is 'openssl aes-256-cbc -a -d' <-- which might be useful to know if you were to lose this app, because OpenSSL doesn't add any pretty info to your encrypted message like GPG, nor is OpenSSL simple-minded enough to decrypt a block of text you pass to it without using the proper arguments." | zenity --text-info --title="$zero [$mode]: Warning" --cancel-label="Understood, don't tell me for a while" --width=724 --height=210 || touch /tmp/$zero.nowarn.$UID
 fi
 
 ## GPG sadly will not overwrite files
 rm $A7/msg* 2>/dev/null
 
 ## Initial main menu choice
-CHOICE=$(zenity --list --radiolist --hide-header --title="$zero [$MODE]" --text="What would you like to do?" --column=1 --column=2 TRUE Encrypt FALSE Decrypt FALSE "Switch to $SWITCH_TO-mode" --cancel-label="Quit") ||	exit
+menu_choice=$(zenity --list --radiolist --hide-header --title="$zero [$mode]" --text="What would you like to do?" --column=1 --column=2 TRUE Encrypt FALSE Decrypt FALSE "Switch to $switch_to-mode" --cancel-label="Quit") ||  exit
 
 ## What did the user pick?
-if [[ $CHOICE = Encrypt ]]; then
-	zenity --text-info --editable --title="$zero [$MODE]: Type or paste text to be encrypted" --width=800 --height=600 --no-wrap >$A7/msg || MAIN
-	zenity --entry --title="$zero [$MODE]" --text="Enter passphrase very carefully" --ok-label="Encrypt" >$A7/pass || MAIN
-	$ENCRYPT
-	>$A7/pass; rm $A7/msg   ## We clear the passphrase & msg buffers ASAP
-	zenity --text-info --title="$zero [$MODE]: Your encrypted text" --width=650 --height=600 --no-wrap --cancel-label="Quit" --ok-label="Menu" <$A7/msg.asc || exit
-	rm $A7/msg.asc
-	MAIN
+if [[ $menu_choice = Encrypt ]]; then
+  zenity --text-info --editable --title="$zero [$mode]: Type or paste text to be encrypted" --width=800 --height=600 --no-wrap >$A7/msg || MAIN
+  zenity --entry --title="$zero [$mode]" --text="Enter passphrase very carefully" --ok-label="Encrypt" >$A7/pass || MAIN
+  $encrypt
+  >$A7/pass; rm $A7/msg   ## We clear the passphrase & msg buffers ASAP
+  zenity --text-info --title="$zero [$mode]: Your encrypted text" --width=650 --height=600 --no-wrap --cancel-label="Quit" --ok-label="Menu" <$A7/msg.asc || exit
+  rm $A7/msg.asc
+  MAIN
 
-elif [[ $CHOICE = Decrypt ]]; then
-	zenity --text-info --editable --title="$zero [$MODE]: Paste $MODE-encrypted message" --width=650 --height=600 --no-wrap >$A7/msg.asc || MAIN
-	zenity --entry --title="$zero [$MODE]" --text "Enter passphrase" --hide-text >$A7/pass || MAIN
-	$DECRYPT
-	>$A7/pass; rm $A7/msg.asc
-	zenity --text-info --title="$zero [$MODE]: Your decrypted text" --width=800 --height=600 --no-wrap --cancel-label="Quit" --ok-label="Menu" <$A7/msg || exit
-	rm $A7/msg
-	MAIN
+elif [[ $menu_choice = Decrypt ]]; then
+  zenity --text-info --editable --title="$zero [$mode]: Paste $mode-encrypted message" --width=650 --height=600 --no-wrap >$A7/msg.asc || MAIN
+  zenity --entry --title="$zero [$mode]" --text "Enter passphrase" --hide-text >$A7/pass || MAIN
+  $decrypt
+  >$A7/pass; rm $A7/msg.asc
+  zenity --text-info --title="$zero [$mode]: Your decrypted text" --width=800 --height=600 --no-wrap --cancel-label="Quit" --ok-label="Menu" <$A7/msg || exit
+  rm $A7/msg
+  MAIN
 
 else
-	if [[ $SWITCH_TO = OpenSSL ]]; then
-		if which openssl &>/dev/null; then
-			init_env_OPENSSL
-		else
-			zenity --error --title="Missing OpenSSL" --text="OpenSSL not found in your \$PATH. That's so shocking I almost don't believe it. In any case, if you really want to try it out, you can install it using your software-management application." --width=400
-		fi
-	elif [[ $SWITCH_TO = GPG ]]; then
-		if which gpg2 &>/dev/null; then
-			init_env_GPG2
-		elif which gpg &>/dev/null; then
-			init_env_GPG
-		else
-			zenity --error --title "Missing GPG" --text 'Neither GPG nor GPG2 were found in your $PATH. You can install either of them using your software-management application.' --width=400
-		fi
-	fi
-	MAIN
+  if [[ $switch_to = OpenSSL ]]; then
+    if hash openssl &>/dev/null; then
+      init_env_OPENSSL
+    else
+      zenity --error --title="Missing OpenSSL" --text="OpenSSL not found in your \$PATH. That's so shocking I almost don't believe it. In any case, if you really want to try it out, you can install it using your software-management application." --width=400
+    fi
+  elif [[ $switch_to = GPG ]]; then
+    if hash gpg2 &>/dev/null; then
+      init_env_GPG2
+    elif hash gpg &>/dev/null; then
+      init_env_GPG
+    else
+      zenity --error --title="Missing GPG" --text='Neither GPG nor GPG2 were found in your $PATH. You can install either of them using your software-management application.' --width=400
+    fi
+  fi
+  MAIN
 fi
 }
 
@@ -121,25 +121,25 @@ fi
 ## BEGINNING                                                                   |
 ##                                                                             |
 if [ $# -ne 0 ]; then                                                       #---
-	echo -e "Provides simple symmetric text encryption/decryption using GPG, GPG2, or OpenSSL\nMeant to be run interactively (no args) from the desktop -- Zenity is required"
-	exit
+  echo -e "Provides simple symmetric text encryption/decryption using GPG, GPG2, or OpenSSL\nMeant to be run interactively (no args) from the desktop -- Zenity is required"
+  exit
 
-elif ! which zenity &>/dev/null; then
-	echo -e "This program relies on Zenity (which you don't have) for user-interaction\nYou can easily install it from your software-management app"
-	exit 1
+elif ! hash zenity &>/dev/null; then
+  echo -e "This program relies on Zenity (which you don't have) for user-interaction\nYou can easily install it from your software-management app"
+  exit 1
 
-elif which gpg2 &>/dev/null; then
-	init_env_GPG2
+elif hash gpg2 &>/dev/null; then
+  init_env_GPG2
 
-elif which gpg &>/dev/null; then
-	init_env_GPG
+elif hash gpg &>/dev/null; then
+  init_env_GPG
 
-elif which openssl &>/dev/null; then
-	init_env_OPENSSL
+elif hash openssl &>/dev/null; then
+  init_env_OPENSSL
 
 else
-	zenity --error --title "You pulling my leg?" --text 'Neither GPG, GPG2, nor OpenSSL were found in your $PATH..? Right. If you say so. Use your software-management application to install one of them.' --width=400
-	exit 1
+  zenity --error --title="You pulling my leg?" --text='Neither GPG, GPG2, nor OpenSSL were found in your $PATH..? Right. If you say so. Use your software-management application to install one of them.' --width=400
+  exit 1
 fi
 
 
